### ISSUE TITLE
Submodule checkout: bridge server could not be cloned

### ISSUE THREAD

**Issue by DaanZ** [waternet/WaternetNautonomous#5]
As a result of cloning WaternetNautonomous and using "git submodule update --init --recursive¨ one of the modules could not be read from the remote repository.

Log:
Submodule path 'src/nautonomous_operation_action': checked out 'fded01713bd3a42894956266bfbc14bc720887fc'
Cloning into 'src/nautonomous_serverconnection_bridge_server'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:waternet/nautonomous_serverconnection_bridge_server.git' into submodule path 'src/nautonomous_serverconnection_bridge_server' failed

**Comment by waternet** [comment]
The bridge_server and logger_server are private repositories for now, and can't be cloned without proper access rights. I think that's what caused this error
